apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-service
spec:
  ports:
    - port: 80
      name: insight
      protocol: TCP
      targetPort: 8001
    - port: 6379
      name: main
      protocol: TCP
      targetPort: 6379      
  selector:
    app: redis
  sessionAffinity: None
  type: ClusterIP
